name: Build python whls
description: Build python wheel packages
inputs:
  name:
    description: Name of the wheel package
    required: true
  os:
    description: Operating system
    required: true

runs:
  using: "composite"
  steps:
    - name: Build with maturin
      run: |
        cd crates/py-bindings
        if [ "${{ inputs.os }}" = "macos" ]; then
              export OPENCV_LINK_LIBS=opencv_core,opencv_imgproc
              export BUILD_FOR_PYTHON=1
        fi
        maturin build --release
      shell: bash

    - name: Install wheel package
      run: pip install wheel
      shell: bash
    - name: Install pefile
      shell: bash
      if: ${{ inputs.os == 'windows' }}
      run: |
        ls target/release/
        ls target/release/ctranslate2-vendor/dyn
        pip install pefile
    - name: Bundle OpenCV only
      if: ${{ inputs.os == 'macos' }}
      shell: bash
      run: |
        pip install wheel delocate
        mkdir -p target/wheels/fixed
        ls target/release/
        export DYLD_LIBRARY_PATH="$(pwd)/target/release/ctranslate2-vendor/dyn:$DYLD_LIBRARY_PATH"
        for whl in target/wheels/rusty_manga_image_translator-*.whl; do
        delocate-wheel -w target/wheels/fixed/ "$whl"
        done

        rm target/wheels/rusty_manga_image_translator-*.whl
        mv target/wheels/fixed/*.whl target/wheels/
        rmdir target/wheels/fixed
    - name: Write inject_dll.py script
      if: ${{ inputs.os != 'macos' }}
      shell: bash
      run: |
        cat > inject_dll.py << 'EOF'
        from wheel.wheelfile import WheelFile
        from pathlib import Path
        from typing import List
        from typing import Optional
        import glob
        import sys
        import re
        import hashlib
        import base64
        import fnmatch
        import os
        import subprocess
        import tempfile

        def find_dlls() -> list[Path]:
            base_dir = Path("target/release")

            if sys.platform.startswith("win"):
                pattern = "onnxruntime_providers_*.dll"
            elif sys.platform == "darwin":
                pattern = "libonnxruntime_providers_*.dylib"
            else:
                pattern = "libonnxruntime_providers_*.so"

            return list(base_dir.glob(pattern))

        def get_opencv_dylib_paths():
            try:
                prefix = subprocess.check_output(["brew", "--prefix", "opencv"], text=True).strip()
                lib_dir = Path(prefix) / "lib"
                pattern = str(lib_dir / "libopencv_*.dylib")
                return [Path(p) for p in glob.glob(pattern)]
            except subprocess.CalledProcessError:
                print("Error: Could not find OpenCV via Homebrew.")
                return []

        def find_binary_in_wheel(wheel: WheelFile, pattern: str) -> Optional[Path]:
            for name in wheel.namelist():
                if name.endswith(pattern):
                    # use a proper temp dir
                    tmp_dir = Path(tempfile.gettempdir())
                    tmp_path = tmp_dir / Path(name).name
                    with wheel.open(name) as src, open(tmp_path, "wb") as dst:
                        dst.write(src.read())
                    return tmp_path
            return None

        def find_dll_on_path(dll_name: str) -> Optional[Path]:
            target_dirs = [Path("target") / "release", Path("C:/tools/opencv")]

            for dir in os.environ['PATH'].split(os.pathsep):
                candidate = Path(dir) / dll_name
                if candidate.exists():
                    return candidate.resolve()

            for base in target_dirs:
              if base.exists():
                for file in base.rglob(dll_name):
                  if file.is_file():
                    return file.resolve()

            return None

        def find_windows_dll(binary_path) -> List[Path]:
            import pefile
            pe = pefile.PE(str(binary_path))
            dll_paths = []

            for entry in pe.DIRECTORY_ENTRY_IMPORT:
                dll_name = entry.dll.decode('utf-8').strip()
                dll_path = find_dll_on_path(dll_name)
                if dll_path:
                    dll_paths.append(dll_path)
                else:
                    print(f"DLL not found in PATH: {dll_name}")
            return dll_paths

        def wheel_paths() -> list[Path]:
            # === Locate wheel ===
            wheel_matches = glob.glob("target/wheels/rusty_manga_image_translator-*.whl")
            if not wheel_matches:
                print("❌ No matching wheel found in target/wheels/")
                sys.exit(1)
            return [Path(x) for x in wheel_matches]

        def generate_info(path):
            with open(path, "rb") as f:
              dll_data = f.read()
              digest = hashlib.sha256(dll_data).digest()
              digest_b64 = base64.urlsafe_b64encode(digest).rstrip(b"=").decode("ascii")
              size = len(dll_data)
              return digest_b64, size

        def get_record_name(original_wheel, record_pattern):
            for name in original_wheel.namelist():
                if fnmatch.fnmatch(name, record_pattern):
                    return name
            return None

        def rewrite(original_wheel, new_wheel, targets_inside_wheel: list[tuple[str, Path, tuple[str, int]]], name: str):
            names = [x[0] for x in targets_inside_wheel]
            names.append(name)
            for name in original_wheel.namelist():
                if name not in names:
                    new_wheel.writestr(name, original_wheel.read(name))
            for target in targets_inside_wheel:
                new_wheel.write(target[1], arcname=target[0])

        for wheel_path in wheel_paths():

            print(f"Found wheel: {wheel_path}")

            # === Set up target path inside wheel ===
            package_root_subdir = "rusty_manga_image_translator"
            dll_list = find_dlls()
            if sys.platform.startswith("linux"):
              targets_inside_wheel = [(f"{package_root_subdir}.libs/{path.name}", path, generate_info(path)) for path in dll_list]
            else:
              targets_inside_wheel = [(f"{package_root_subdir}/{path.name}", path, generate_info(path)) for path in dll_list]

            tmp_wheel_path = wheel_path.with_name(wheel_path.stem + "_tmp.whl")

            with WheelFile(wheel_path, 'r') as original_wheel:
                with WheelFile(tmp_wheel_path, 'w') as new_wheel:
                    record_pattern = 'rusty_manga_image_translator-*.dist-info/RECORD'
                    record_name = get_record_name(original_wheel, record_pattern)
                    if record_name is None:
                        raise ValueError("RECORD file not found")

                    if sys.platform.startswith("win"):
                        binary_path = find_binary_in_wheel(original_wheel, 'rusty_manga_image_translator.pyd')
                        if binary_path is None:
                          raise FileNotFoundError("Could not find the binary inside the wheel")
                        dll_list.extend(find_windows_dll(binary_path))
                    rewrite(original_wheel, new_wheel, targets_inside_wheel, record_name)
                    if record_name:
                        record_content = original_wheel.read(record_name).decode('utf-8')
                        lines = record_content.splitlines()
                        record_line = "\n".join([f"{x[0]},sha256={x[2][0]},{x[2][1]}" for x in targets_inside_wheel])
                        if lines and not lines[-1].strip():
                            lines.insert(-1, record_line.strip())
                        else:
                            lines.append(record_line.strip())

                        new_record_content = '\n'.join(lines) + '\n'
                        new_wheel.writestr(record_name, new_record_content)
                    else:
                        raise ValueError("RECORD file not found")
            tmp_wheel_path.replace(wheel_path)
            print(f"Wheel updated in-place: {wheel_path}")

        EOF

    - name: Inject DLL into wheel
      if: ${{ inputs.os != 'macos' }}
      shell: bash
      run: python inject_dll.py
