name: Setup Linux

inputs:
  runs-on:
    required: false

runs:
  using: "composite"
  steps:
    - name: Maximize build space
      if: ${{ inputs.runs-on == 'ubuntu-latest' }}
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 16384
        remove-dotnet: "true"
        remove-android: "true"
        remove-codeql: "true"
        remove-docker-images: "true"
        remove-haskell: "true"
    - name: Install dependencies
      shell: bash
      run: |
        echo "Free space:"
        df -h
        sudo apt-get update
        sudo apt-get install -y pkg-config libssl-dev libopencv-dev clang libclang-dev libfontconfig-dev
