name: Release Action

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: linux-x86_64
            runs-on: ubuntu-22.04
            os: linux
          - name: linux-arm64
            runs-on: ubuntu-24.04-arm
            os: linux
          - name: macos-arm64
            runs-on: macos-latest
            os: macos
          - name: macos-x86_64
            runs-on: macos-13
            os: macos
          - name: windows-x86_64
            runs-on: windows-latest
            os: windows

    name: Setup on ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.runs-on }}

    steps:
      - name: Checkout code
        if: matrix.platform.name != 'linux-x86_64'
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Checkout only .github files
        if: matrix.platform.name == 'linux-x86_64'
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
          sparse-checkout-cone-mode: false
      - name: Setup Linux
        if: matrix.platform.name == 'linux-x86_64' || matrix.platform.name == 'linux-arm64'
        uses: ./.github/actions/setup-linux
        with:
          runs-on: ${{ matrix.platform.runs-on }}
      - name: Checkout code
        if: matrix.platform.name == 'linux-x86_64'
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup macOS
        if: matrix.platform.name == 'macos-arm64' || matrix.platform.name == 'macos-x86_64'
        uses: ./.github/actions/setup-macos
        with:
          runs-on: ${{ matrix.platform.runs-on }}

      - name: Setup Windows
        if: matrix.platform.name == 'windows-x86_64'
        uses: ./.github/actions/setup-windows
        with:
          runs-on: ${{ matrix.platform.runs-on }}

      - name: Setup Rust
        uses: ./.github/actions/setup-rust

      - name: Set up Pythons
        if: matrix.platform.os != 'windows'
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Setup Python
        id: setup-python
        uses: ./.github/actions/setup-python

      - name: Tests & Building
        uses: ./.github/actions/cargo
        with:
          test: matrix.platform.os != 'windows'
          runs-on: ${{ matrix.platform.runs-on }}
          os: ${{  matrix.platform.os }}
          name: ${{ matrix.platform.name }}

      - name: Build wheels
        uses: ./.github/actions/python-build
        with:
          name: ${{ matrix.platform.name }}
          os: ${{ matrix.platform.os }}

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.platform.name }}
          path: target/wheels/*.whl
          retention-days: 5

  release:
    needs:
      - build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Prepare Release Archives
        shell: bash
        run: |
          for target in linux-x86_64 linux-arm64 windows-x86_64 macos-x86_64 macos-arm64; do
            if [[ "$target" == "windows-x86_64" ]]; then
              zip -r "manga-image-translator-$target.zip" "$target"/*
            else
              tar -C "$target" -czf "manga-image-translator-$target.tar.gz" .
            fi
          done

      - name: Create Release
        uses: softprops/action-gh-release@v1
        # wheels-*/rusty_manga_image_translator-*.whl
        with:
          files: |
            release/manga-image-translator-*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: PyPI Release
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          pip install --upgrade twine
          find wheels-* -name "*.whl" -print0 | xargs -0 twine upload --skip-existing
